---
- hosts: all
  tasks:
  - name: Install SSH keys
    authorized_key:
      user: root
      key: "{{ item }}"
    loop: "{{ ssh_keys }}"

  - name: Create ansible-pull cron job
    cron:
      name: "run ansible-pull"
      cron_file: "ansible-pull"
      user: "root"
      minute: "*/15"
      job: "/usr/local/bin/ansible-pull provision.yml -U {{ ansible_pull_repo }} -i 'localhost,'"

  - name: Install basic packages
    package:
      name: "{{ item }}"
      state: present
    loop: "{{ basic_packages }}"

  - name: Enable vim plugins
    uri:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: /root/.vim/autoload/plug.vim

  - name: Install vim plugins
    git:
      repo: "{{ item }}"
      dest: /root/.vim/bundle/nerdtree
      update: no
    loop:
    - https://github.com/scrooloose/nerdtree.git

  - name: Setup vimrc
    copy:
      src: vimrc
      dest: /root/.vimrc
      owner: root
      group: root
      mode: "0644"
...