---
- hosts: all
  tasks:
  - name: Install SSH keys
    authorized_key:
      user: root
      key: "{{ item }}"
    loop: "{{ ssh_keys }}"

  - name: Create ansible-pull cron job
    cron:
      name: "run ansible-pull"
      cron_file: "ansible-pull"
      user: "root"
      minute: "*/15"
      job: "/usr/local/bin/ansible-pull provision.yml -U {{ ansible_pull_repo }} -i 'localhost,'"

  - name: Install basic packages
    package:
      name: "{{ item }}"
      state: present
    loop: "{{ basic_packages }}"
...